dragndrop задачи
alfiya-udc/ru.javascript.info pull request #1
Opened 2019-06-24 21:47 UTC by alfill

2019-06-24 23:50 UTC, alfill commented
остались комментарии в /2-drag-heroes/solution.view/soccer.js, [старый вариант](https://next.plnkr.co/edit/wMXFrZ7owuBI8STOcl0M?preview) переводов в решении, если поможет

2019-06-28 05:45 UTC, alfiya-udc requested changes

2019-06-28 05:45 UTC, alfiya-udc commented on 2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/solution.md
> +Бегунок немного поднят, и вылезает по высоте из родителя.
убрать запятую

2019-06-28 05:45 UTC, alfiya-udc commented on 2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/solution.md
> +В этом случае мы реализуем горизонтальный Drag'n'Drop, ограниченный по ширине. Его особенность – в `position:relative` у переносимого элемента, т.е. координата ставится не абсолютная, а относительно
т.е. координаты ставятся не абсолютные, а относительно родителя

2019-06-28 05:45 UTC, alfiya-udc commented on 2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/task.md
> +Захватите мышкой за синий бегунок и поперемещайте его.
-за

2019-06-28 05:45 UTC, alfiya-udc commented on 2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/task.md
> +- Слайдер должен нормально работать при резком движении мыши влево или вправо, за пределы полосы. При этом бегунок должен останавливаться четко в нужном конце полосы.
убрать запятую, +ё

2019-06-28 05:45 UTC, alfiya-udc commented on 2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/task.md
и DOM

2019-06-28 08:14 UTC, alfill reviewed
исправления опечаток.

2019-06-28 08:14 UTC, alfill commented on 2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/solution.md
> +Бегунок немного поднят, и вылезает по высоте из родителя.
```suggestion
Бегунок немного поднят и вылезает по высоте из родителя.
```

2019-06-28 08:14 UTC, alfill commented on 2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/solution.md
> +В этом случае мы реализуем горизонтальный Drag'n'Drop, ограниченный по ширине. Его особенность – в `position:relative` у переносимого элемента, т.е. координата ставится не абсолютная, а относительно
```suggestion
В этом случае мы реализуем горизонтальный Drag'n'Drop, ограниченный по ширине. Его особенность – в `position:relative` у переносимого элемента, т.е. координаты ставится не абсолютные, а относительно родителя.
```

2019-06-28 08:14 UTC, alfill commented on 2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/task.md
> +Захватите мышкой за синий бегунок и поперемещайте его.
```suggestion
Захватите мышкой синий бегунок и поперемещайте его. 
```

2019-06-28 08:14 UTC, alfill commented on 2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/task.md
> +- Слайдер должен нормально работать при резком движении мыши влево или вправо, за пределы полосы. При этом бегунок должен останавливаться четко в нужном конце полосы.
```suggestion
- Слайдер должен нормально работать при резком движении мыши влево или вправо за пределы полосы. При этом бегунок должен останавливаться чётко в нужном конце полосы.
```

2019-06-28 08:14 UTC, alfill commented on 2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/task.md
> +В этой задаче вы можете проверить своё понимание сразу нескольких аспектов Drag’n’Drop.
```suggestion
В этой задаче вы можете проверить своё понимание сразу нескольких аспектов Drag’n’Drop и DOM.
```

2019-06-28 08:19 UTC, alfill commented on 2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/solution.md
> +В этом случае мы реализуем горизонтальный Drag'n'Drop, ограниченный по ширине. Его особенность – в `position:relative` у переносимого элемента, т.е. координата ставится не абсолютная, а относительно
```suggestion
В этом случае мы реализуем горизонтальный Drag'n'Drop, ограниченный по ширине. Его особенность – в `position:relative` у переносимого элемента, т.е. координаты ставятся не абсолютные, а относительно родителя.
```

2019-06-28 08:21 UTC, alfill commented on 2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/solution.md
> +В этом случае мы реализуем горизонтальный Drag'n'Drop, ограниченный по ширине. Его особенность – в `position:relative` у переносимого элемента, т.е. координата ставится не абсолютная, а относительно
fix

2019-06-28 08:24 UTC, alfill commented on 2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/solution.md
> +В этом случае мы реализуем горизонтальный Drag'n'Drop, ограниченный по ширине. Его особенность – в `position:relative` у переносимого элемента, т.е. координата ставится не абсолютная, а относительно
ну вот, невозможно преобразовать в коммит - outdated suggestion cannnot be applied.

2019-06-28 08:33 UTC, alfill reviewed
fix исправления

2019-06-28 08:38 UTC, alfill commented
тут включены 'Allow edits from maintainers'. 
> If checked, users with write access to alfiya-udc/ru.javascript.info can add new commits to your patch-1 branch.

2019-06-28 09:11 UTC, alfiya-udc approved these changes

2019-06-28 09:12 UTC, merged